---
title: "seurat_tutorial"
output: html_document
date: "2025-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## seurat tutorial
Voor het project gaan we analyses uitvoeren met Seurat. Om kennis te maken met het progamma wordt er een [tutorial](https://satijalab.org/seurat/articles/pbmc3k_tutorial) uitgevoerd van Seurat.

```{r loading the library, include=FALSE}
#laad de volgende pakketen in. 
library(dplyr)
library(Seurat)
library(patchwork)
```

```{r loading dataset, include=FALSE}
# data inladen als een object. 
pbmc.data <- Read10X(data.dir = "~/lncRNA_sc_splice/raw_data/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc
```

```{r pre-procesing, warning=FALSE}
# extra collum aanmaken waar het pecentage mitochondriaal RNA berekend wordt. cellen die lage kwaliteit hebben vertonen vaak een hoog percentage mitochondriaal RNA. extra colom wordt gemaakt met [[]]

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
head(pbmc, 50)

# visulaiseren van de data. dit kan gedaan worden in een violin plot. ncol staat voor de nummer van collomen. 
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)


# met een featurescatter kan er gevisulaiseerd worden wat de relatie is tussen verschillende features.
plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1
plot2

# de cellen worden gefilterd op feature count van meer dan 2500 of minder dan 200. Er word ook gefilterd op minder dan 5% mitochondriaal pecentage
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
head(pbmc, 50)
```


